extends: default

ignore: |
  skills/splunk-connect-for-snmp-setup/templates/compose/docker-compose.yml
  skills/splunk-connect-for-snmp-setup/templates/kubernetes/namespace.yaml
  skills/splunk-connect-for-snmp-setup/templates/kubernetes/values.yaml
  skills/splunk-connect-for-syslog-setup/templates/host/docker-compose.yml
  skills/splunk-connect-for-syslog-setup/templates/kubernetes/namespace.yaml
  skills/splunk-connect-for-syslog-setup/templates/kubernetes/values.yaml

rules:
  line-length:
    max: 200
  truthy:
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1
