#!/usr/bin/env python3
"""Render or verify the security portfolio table derived from catalog.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_CATALOG = SCRIPT_DIR.parent / "catalog.json"
DEFAULT_REFERENCE = SCRIPT_DIR.parent / "reference.md"
START_MARKER = "<!-- BEGIN GENERATED SECURITY PORTFOLIO TABLE -->"
END_MARKER = "<!-- END GENERATED SECURITY PORTFOLIO TABLE -->"


def markdown_cell(value: object) -> str:
    text = str(value).replace("\\", "\\\\").replace("|", "\\|")
    return " ".join(text.splitlines())


def code_list(values: list[str]) -> str:
    return ", ".join(f"`{markdown_cell(value)}`" for value in values) or "N/A"


def source_list(values: list[str]) -> str:
    return ", ".join(
        f"[{index}]({markdown_cell(value)})" for index, value in enumerate(values, start=1)
    ) or "N/A"


def render_table(catalog: dict[str, object]) -> str:
    lines = [
        START_MARKER,
        "<!-- Generated by scripts/render_reference_table.py; edit catalog.json, not these rows. -->",
        f"`last_verified: {markdown_cell(catalog.get('last_verified', 'unknown'))}`",
        "",
        "| Product | Catalog key | Status | Local route | Splunkbase IDs | Sources | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for raw_entry in catalog.get("entries", []):
        entry = dict(raw_entry)
        lines.append(
            "| "
            + " | ".join(
                [
                    markdown_cell(entry["name"]),
                    f"`{markdown_cell(entry['key'])}`",
                    f"`{markdown_cell(entry['status'])}`",
                    code_list(entry.get("route", [])),
                    code_list(entry.get("splunkbase_ids", [])),
                    source_list(entry.get("source_urls", [])),
                    markdown_cell(entry.get("notes", "")),
                ]
            )
            + " |"
        )
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_generated_table(reference: str, generated: str) -> str:
    if reference.count(START_MARKER) != 1 or reference.count(END_MARKER) != 1:
        raise ValueError(
            "reference must contain exactly one generated-table start and end marker"
        )
    start = reference.index(START_MARKER)
    end = reference.index(END_MARKER, start) + len(END_MARKER)
    return reference[:start] + generated + reference[end:]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render or verify the catalog-derived security coverage table."
    )
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--reference", type=Path, default=DEFAULT_REFERENCE)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Fail if reference.md is stale.")
    mode.add_argument("--write", action="store_true", help="Update reference.md in place.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    generated = render_table(catalog)
    if not args.check and not args.write:
        print(generated)
        return 0

    reference = args.reference.read_text(encoding="utf-8")
    try:
        expected = replace_generated_table(reference, generated)
    except ValueError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if reference != expected:
            print(
                "FAIL: security portfolio reference table is stale; run "
                "scripts/render_reference_table.py --write",
                file=sys.stderr,
            )
            return 1
        print("PASS: security portfolio reference table matches catalog.json")
        return 0

    args.reference.write_text(expected, encoding="utf-8")
    print(f"Updated {args.reference}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
