#!/usr/bin/env bash
set -euo pipefail

# Splunk Observability Cloud GCP Integration Setup
#
# Render-first CLI — mirrors splunk-observability-aws-integration:
#   --render (default), --apply [SECTIONS], --validate [--live],
#   --doctor, --discover, --quickstart, --quickstart-from-live,
#   --explain, --rollback [ACTION], --list-services
#
# File-based secrets only. The Splunk O11y token and GCP SA key are read from
# chmod-600 files. The official Splunk-generated WIF JSON is read from a
# mode-600 file. Credential contents are never passed in argv.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../../shared/lib/credential_helpers.sh"

PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
RENDERER="${SCRIPT_DIR}/render_assets.py"
SKILL_NAME="splunk-observability-gcp-integration"
DEFAULT_RENDER_DIR_NAME="splunk-observability-gcp-integration-rendered"

PYTHON_BIN="python3"
if [[ -x "${PROJECT_ROOT}/.venv/bin/python" ]]; then
    PYTHON_BIN="${PROJECT_ROOT}/.venv/bin/python"
fi

MODE="render"
PRIMARY_MODE=""
MODE_CONFLICT=false
APPLY_REQUESTED=false
ROLLBACK_REQUESTED=false
ROLLBACK_ACTION_EXPLICIT=false
ROLLBACK_INTEGRATION_ALIAS=false
SECTIONS=""
ROLLBACK_ACTION=""
SPEC=""
OUTPUT_DIR=""
REALM=""
TOKEN_FILE=""
KEY_FILES=()
WIF_CONFIG_FILE=""
INTEGRATION_ID=""
INTEGRATION_NAME=""
EXPECTED_ENABLED_STATE="true"
PLAN_FILE=""
PLAN_SHA256=""
OBSERVED_STATE_FILE=""
ACKNOWLEDGE_DISABLE=""
ACKNOWLEDGE_DELETE=""
ALLOW_LOOSE_TOKEN_PERMS=false
JSON_OUTPUT=false
DRY_RUN=false

usage() {
    local exit_code="${1:-0}"
    cat <<EOF
Splunk Observability Cloud — GCP Integration Setup

Usage: $(basename "$0") [MODE] [OPTIONS]

Modes (pick one; --render is the default):
  --render                       Produce the numbered plan tree under --output-dir.
  --apply [SECTIONS]             Call POST/PUT /v2/integration. Sections: integration,validation.
  --validate [--live]            Static checks; --live adds probe GET /v2/integration.
  --doctor                       Validate services, poll-rate, namedToken, credential-hash.
  --discover                     Capture a private, fully paginated count/results snapshot.
  --quickstart                   Render + print exact --apply command.
  --quickstart-from-live         Capture live state/current-state.json and print a handoff.
  --explain                      Print the apply plan in plain English; no API calls.
  --rollback [ACTION]            Render an offline plan. ACTION: disable, delete;
                                 integration is a deprecated alias for disable.
                                 Bare --rollback renders disable but cannot apply.
  --list-services                Print the supported GCP services enum (32 entries).

Spec / output:
  --spec PATH                    Spec file (YAML or JSON); defaults to template.example.
  --output-dir PATH              Output directory; defaults to ${DEFAULT_RENDER_DIR_NAME}.
  --realm REALM                  Override spec.realm.

File-based secrets (chmod 600 enforced):
  --token-file PATH              Org/API token for GET; admin session/User token for mutation.
  --key-file PATH                GCP SA JSON; repeat as needed, mapped by file project_id.
  --wif-config-file PATH         Official generated gcp_wif_config.json (mode 600).
  --allow-loose-token-perms      Non-rollback compatibility only; rollback rejects it.

Rollback review/apply flags:
  --integration-id ID            Exact server-assigned integration ID; names never mutate.
  --integration-name NAME        Required exact expected name; never inferred from a spec.
  --expected-enabled-state BOOL  Pre-mutation Boolean bound into a new plan (default: true).
  --plan-file PATH               Mode-600 rollback plan (default: output state/rollback-plan.json).
  --observed-state-file PATH     Mode-600 discover snapshot bound during offline plan render.
  --plan-hash SHA256             Canonical reviewed plan digest; required for mutation.
  --accept-disable-integration ID  Required only for disable; must equal integration ID.
  --accept-delete-integration ID   Required only for delete; must equal integration ID.
  Mutation also requires --apply. Disable and delete are separately planned actions.

Behaviour flags:
  --dry-run                      Skip live API calls; render only.
  --json                         Machine-readable result.
  -h | --help                    Show this help.

Direct-secret flags below are REJECTED:
  --secret --password --api-key --project-key --token --wif-config

Examples:
  # Render from template.example:
  bash $0 --realm us1

  # Full apply:
  bash $0 --apply --spec my-spec.yaml --realm us1 \\
    --token-file /tmp/splunk_token \\
    --key-file /tmp/gcp-sa-key.json

  # WIF apply. Use the unmodified file generated by Splunk:
  bash $0 --apply --spec my-wif-spec.yaml --realm us1 \\
    --token-file /tmp/splunk_token \\
    --wif-config-file /secure/path/gcp_wif_config.json

  # Capture the trusted snapshot used by rollback review:
  bash $0 --discover --realm us1 --token-file /secure/o11y-read-token \\
    --output-dir gcp-live

  # Render a disable plan offline (the default rollback behavior):
  bash $0 --rollback disable --realm us1 \\
    --integration-id SERVER_ID --integration-name EXPECTED_NAME \\
    --observed-state-file /secure/current-state.json \\
    --key-file /secure/project-a.json  # repeat once per project; or use WIF file

  # Apply only that reviewed plan (HASH is printed by the render command):
  bash $0 --rollback disable --apply --realm us1 --integration-id SERVER_ID \\
    --plan-file PATH --plan-hash HASH --accept-disable-integration SERVER_ID \\
    --token-file /secure/o11y-token --key-file /secure/project-a.json

  # Delete is separately reviewed and accepts no GCP credential files:
  bash $0 --rollback delete --realm us1 --integration-id SERVER_ID \\
    --integration-name EXPECTED_NAME --expected-enabled-state false \\
    --observed-state-file /secure/current-state.json --plan-file /secure/delete-plan.json
EOF
    exit "${exit_code}"
}

reject_direct_secret() {
    local name="$1"
    cat >&2 <<EOF
Refusing direct-secret flag --${name}. Use file-based equivalents:
  --key-file PATH       GCP Service Account JSON key file
  --wif-config-file PATH  Official Splunk-generated gcp_wif_config.json
  --token-file PATH     Splunk O11y API access token
See skills/${SKILL_NAME}/SKILL.md for credential setup instructions.
EOF
    exit 2
}

record_primary_mode() {
    local requested="$1"
    if [[ -n "${PRIMARY_MODE}" && "${PRIMARY_MODE}" != "${requested}" ]]; then
        MODE_CONFLICT=true
    elif [[ -z "${PRIMARY_MODE}" ]]; then
        PRIMARY_MODE="${requested}"
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --render) record_primary_mode "render" ;;
        --apply)
            APPLY_REQUESTED=true
            if [[ $# -ge 2 && "$2" != --* ]]; then
                SECTIONS="$2"; shift
            fi
            ;;
        --validate) record_primary_mode "validate" ;;
        --live) export SGCP_VALIDATE_LIVE=true ;;
        --doctor) record_primary_mode "doctor" ;;
        --discover) record_primary_mode "discover" ;;
        --quickstart) record_primary_mode "quickstart" ;;
        --quickstart-from-live) record_primary_mode "quickstart_from_live" ;;
        --explain) record_primary_mode "explain" ;;
        --rollback)
            ROLLBACK_REQUESTED=true
            record_primary_mode "rollback"
            if [[ $# -ge 2 && "$2" != --* ]]; then
                case "$2" in
                    disable|delete) ROLLBACK_ACTION="$2"; ROLLBACK_ACTION_EXPLICIT=true; shift ;;
                    integration)
                        ROLLBACK_ACTION="disable"
                        ROLLBACK_ACTION_EXPLICIT=true
                        ROLLBACK_INTEGRATION_ALIAS=true
                        shift
                        ;;
                esac
            fi
            ;;
        --integration-id) INTEGRATION_ID="$2"; shift ;;
        --integration-name) INTEGRATION_NAME="$2"; shift ;;
        --expected-enabled-state) EXPECTED_ENABLED_STATE="$2"; shift ;;
        --plan-file) PLAN_FILE="$2"; shift ;;
        --plan-hash) PLAN_SHA256="$2"; shift ;;
        --observed-state-file) OBSERVED_STATE_FILE="$2"; shift ;;
        --accept-disable-integration) ACKNOWLEDGE_DISABLE="$2"; shift ;;
        --accept-delete-integration) ACKNOWLEDGE_DELETE="$2"; shift ;;
        --list-services) record_primary_mode "list_services" ;;
        --spec) SPEC="$2"; shift ;;
        --output-dir) OUTPUT_DIR="$2"; shift ;;
        --realm) REALM="$2"; shift ;;
        --token-file) TOKEN_FILE="$2"; shift ;;
        --key-file) KEY_FILES+=("$2"); shift ;;
        --wif-config-file) WIF_CONFIG_FILE="$2"; shift ;;
        --allow-loose-token-perms) ALLOW_LOOSE_TOKEN_PERMS=true ;;
        --dry-run) DRY_RUN=true ;;
        --json) JSON_OUTPUT=true ;;
        --secret|--password|--api-key|--project-key|--token|--wif-config|--secret=*|--password=*|--api-key=*|--project-key=*|--token=*|--wif-config=*)
            rejected_flag="${1%%=*}"
            reject_direct_secret "${rejected_flag#--}"
            ;;
        -h|--help) usage 0 ;;
        *) echo "Unknown option: ${1%%=*}" >&2; usage 1 ;;
    esac
    shift
done

if [[ "${MODE_CONFLICT}" == "true" ]]; then
    echo "ERROR: conflicting primary modes were requested." >&2
    exit 2
fi
if [[ "${ROLLBACK_REQUESTED}" == "true" ]]; then
    MODE="rollback"
    [[ -z "${ROLLBACK_ACTION}" ]] && ROLLBACK_ACTION="disable"
elif [[ "${APPLY_REQUESTED}" == "true" ]]; then
    if [[ -n "${PRIMARY_MODE}" ]]; then
        echo "ERROR: --apply conflicts with a separate primary mode." >&2
        exit 2
    fi
    MODE="apply"
elif [[ -n "${PRIMARY_MODE}" ]]; then
    MODE="${PRIMARY_MODE}"
fi

if [[ -z "${SPEC}" ]]; then
    SPEC="${SCRIPT_DIR}/../template.example"
fi
if [[ -z "${OUTPUT_DIR}" ]]; then
    OUTPUT_DIR="${PROJECT_ROOT}/${DEFAULT_RENDER_DIR_NAME}"
fi
if [[ -z "${PLAN_FILE}" ]]; then
    PLAN_FILE="${OUTPUT_DIR}/state/rollback-plan.json"
fi

if [[ "${MODE}" != "rollback" ]]; then
    load_observability_cloud_settings
    if [[ -z "${REALM}" && -n "${SPLUNK_O11Y_REALM:-}" ]]; then
        REALM="${SPLUNK_O11Y_REALM}"
    fi
    if [[ -z "${TOKEN_FILE}" && -n "${SPLUNK_O11Y_TOKEN_FILE:-}" ]]; then
        TOKEN_FILE="${SPLUNK_O11Y_TOKEN_FILE}"
    fi
fi

file_mode_octal() {
    local path="$1"
    "${PYTHON_BIN}" - "${path}" <<'PY'
import os, stat, sys
try:
    metadata = os.stat(sys.argv[1])
except OSError:
    raise SystemExit("FAIL: credential file metadata could not be read safely")
print(format(stat.S_IMODE(metadata.st_mode), "03o"))
PY
}

assert_secret_file_perms() {
    local path="$1"
    local label="$2"
    [[ -z "${path}" ]] && return 0
    if [[ -L "${path}" || ! -f "${path}" ]]; then
        echo "FAIL: ${label} file is missing, symlinked, or not regular." >&2; exit 2
    fi
    if [[ ! -s "${path}" ]]; then
        echo "FAIL: ${label} file is empty." >&2; exit 2
    fi
    local mode
    mode="$(file_mode_octal "${path}")"
    if [[ "${mode}" != "600" ]]; then
        if [[ "${ALLOW_LOOSE_TOKEN_PERMS}" == "true" ]]; then
            echo "WARN: ${label} file has loose permissions (${mode}); proceeding under --allow-loose-token-perms." >&2
        else
            echo "FAIL: ${label} file has loose permissions (${mode}); mode 600 is required." >&2; exit 2
        fi
    fi
}

assert_wif_config_file() {
    local path="$1"
    if [[ -z "${path}" ]]; then
        echo "FAIL: WIF mode requires the official generated gcp_wif_config.json file." >&2
        exit 2
    fi
    "${PYTHON_BIN}" - "${path}" <<'PY'
import json
import stat
import sys
from pathlib import Path

path = Path(sys.argv[1])
if path.name != "gcp_wif_config.json":
    raise SystemExit("FAIL: WIF config must be named gcp_wif_config.json")
try:
    metadata = path.lstat()
except OSError:
    raise SystemExit("FAIL: WIF config is missing or unreadable")
if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
    raise SystemExit("FAIL: WIF config must be a regular file, not a symlink")
mode = stat.S_IMODE(metadata.st_mode)
if mode != 0o600:
    raise SystemExit(f"FAIL: WIF config must have mode 600, found {oct(mode)}")
try:
    payload = json.loads(path.read_text(encoding="utf-8"))
except (OSError, UnicodeError, json.JSONDecodeError):
    raise SystemExit("FAIL: WIF config is not valid UTF-8 JSON")
if not isinstance(payload, dict) or not payload:
    raise SystemExit("FAIL: WIF config must contain a non-empty JSON object")
PY
}

run_renderer() {
    local args=("--spec" "${SPEC}" "--output-dir" "${OUTPUT_DIR}")
    [[ -n "${REALM}" ]] && args+=("--realm" "${REALM}")
    local key_file
    for key_file in "${KEY_FILES[@]}"; do args+=("--key-file" "${key_file}"); done
    [[ -n "${WIF_CONFIG_FILE}" ]] && args+=("--wif-config-file" "${WIF_CONFIG_FILE}")
    [[ "${JSON_OUTPUT}" == "true" ]] && args+=("--json")
    "${PYTHON_BIN}" "${RENDERER}" "${args[@]}"
}

run_validate() {
    local args=(--output-dir "${OUTPUT_DIR}")
    [[ "${SGCP_VALIDATE_LIVE:-}" == "true" ]] && args+=(--live)
    [[ -n "${TOKEN_FILE}" ]] && args+=(--token-file "${TOKEN_FILE}")
    [[ "${JSON_OUTPUT}" == "true" ]] && args+=(--json)
    bash "${SCRIPT_DIR}/validate.sh" "${args[@]}"
}

run_doctor() {
    local args=(--output-dir "${OUTPUT_DIR}" --realm "${REALM:-us1}")
    [[ "${JSON_OUTPUT}" == "true" ]] && args+=(--json)
    bash "${SCRIPT_DIR}/doctor.sh" "${args[@]}"
}

case "${MODE}" in
    render)
        run_renderer
        ;;
    explain)
        run_renderer
        echo ""
        echo "==> Review the rendered plan in: ${OUTPUT_DIR}"
        echo "==> When ready, apply with:"
        explain_auth="$("${PYTHON_BIN}" - "${OUTPUT_DIR}/rest/create.json" <<'PY'
import json, sys
print(json.load(open(sys.argv[1], encoding="utf-8")).get("authMethod", ""))
PY
)"
        if [[ "${explain_auth}" == "WORKLOAD_IDENTITY_FEDERATION" ]]; then
            credential_hint="--wif-config-file /secure/path/gcp_wif_config.json"
        else
            credential_hint="--key-file /tmp/gcp-sa-key.json"
        fi
        echo "    bash ${0} --apply --spec ${SPEC} --realm ${REALM:-<realm>} --token-file /tmp/splunk_token ${credential_hint}"
        ;;
    apply)
        if [[ -z "${TOKEN_FILE}" ]]; then
            echo "ERROR: --apply requires --token-file." >&2
            exit 2
        fi
        assert_secret_file_perms "${TOKEN_FILE}" "Splunk O11y token"
        for key_file in "${KEY_FILES[@]}"; do assert_secret_file_perms "${key_file}" "GCP SA key"; done
        run_renderer
        local_sections="${SECTIONS}"
        if [[ -z "${local_sections}" ]]; then
            local_sections="integration,validation"
        fi
        IFS=',' read -ra _sects <<< "${local_sections}"
        for s in "${_sects[@]}"; do
            s="${s// /}"
            [[ -z "${s}" ]] && continue
            echo "==> applying section: ${s}"
            case "${s}" in
                integration)
                    auth_method="$("${PYTHON_BIN}" - "${OUTPUT_DIR}/rest/create.json" <<'PY'
import json, sys
print(json.load(open(sys.argv[1], encoding="utf-8")).get("authMethod", ""))
PY
)"
                    credential_args=()
                    case "${auth_method}" in
                        SERVICE_ACCOUNT_KEY)
                            while IFS= read -r key_file; do
                                [[ -z "${key_file}" ]] && continue
                                assert_secret_file_perms "${key_file}" "GCP SA key"
                                credential_args+=(--key-file "${key_file}")
                            done < <("${PYTHON_BIN}" - "${OUTPUT_DIR}/rest/project-key-file-manifest.json" <<'PY'
import json, sys
for item in json.load(open(sys.argv[1])):
    print(item.get("keyFile", ""))
PY
)
                            ;;
                        WORKLOAD_IDENTITY_FEDERATION)
                            rendered_wif_file="$("${PYTHON_BIN}" - "${OUTPUT_DIR}/rest/wif-config-file-manifest.json" <<'PY'
import json, sys
print(json.load(open(sys.argv[1], encoding="utf-8")).get("configFile", ""))
PY
)"
                            assert_wif_config_file "${rendered_wif_file}"
                            credential_args+=(--wif-config-file "${rendered_wif_file}")
                            ;;
                        *)
                            echo "FAIL: unsupported rendered authMethod: ${auth_method}" >&2
                            exit 2
                            ;;
                    esac
                    api_args=()
                    [[ "${DRY_RUN}" == "true" ]] && api_args+=(--dry-run)
                    [[ "${ALLOW_LOOSE_TOKEN_PERMS}" == "true" ]] && api_args+=(--allow-loose-token-perms)
                    "${PYTHON_BIN}" "${SCRIPT_DIR}/gcp_integration_api.py" \
                        --realm "${REALM:-us1}" \
                        --token-file "${TOKEN_FILE}" \
                        "${credential_args[@]}" \
                        --payload-file "${OUTPUT_DIR}/rest/create.json" \
                        --state-dir "${OUTPUT_DIR}/state" \
                        "${api_args[@]}" \
                        upsert
                    ;;
                validation)
                    run_validate
                    ;;
                *)
                    echo "Unknown section: ${s}" >&2; exit 2
                    ;;
            esac
        done
        ;;
    validate)
        run_validate
        ;;
    doctor)
        run_renderer
        run_doctor
        ;;
    discover)
        if [[ -z "${TOKEN_FILE}" ]]; then
            echo "ERROR: --token-file is required for --discover." >&2; exit 2
        fi
        assert_secret_file_perms "${TOKEN_FILE}" "Splunk O11y token"
        "${PYTHON_BIN}" "${SCRIPT_DIR}/gcp_integration_api.py" \
            --realm "${REALM:-us1}" \
            --token-file "${TOKEN_FILE}" \
            --state-dir "${OUTPUT_DIR}/state" \
            --output "${OUTPUT_DIR}/state/current-state.json" \
            discover
        echo "==> Written to ${OUTPUT_DIR}/state/current-state.json"
        ;;
    quickstart)
        echo "==> Quickstart: rendering plan from ${SPEC}..."
        run_renderer
        echo ""
        echo "==> Plan rendered to: ${OUTPUT_DIR}"
        echo ""
        echo "==> Review the REST payload and Terraform, then apply:"
        echo "    bash ${0} --apply --spec ${SPEC} --realm ${REALM:-<realm>} \\"
        echo "      --token-file /tmp/splunk_token \\"
        quickstart_auth="$("${PYTHON_BIN}" - "${OUTPUT_DIR}/rest/create.json" <<'PY'
import json, sys
print(json.load(open(sys.argv[1], encoding="utf-8")).get("authMethod", ""))
PY
)"
        if [[ "${quickstart_auth}" == "WORKLOAD_IDENTITY_FEDERATION" ]]; then
            echo "      --wif-config-file /secure/path/gcp_wif_config.json"
        else
            echo "      --key-file /tmp/gcp-sa-key.json"
        fi
        ;;
    quickstart_from_live)
        if [[ -z "${TOKEN_FILE}" ]]; then
            echo "ERROR: --token-file is required for --quickstart-from-live." >&2; exit 2
        fi
        assert_secret_file_perms "${TOKEN_FILE}" "Splunk O11y token"
        mkdir -p "${OUTPUT_DIR}/state"
        "${PYTHON_BIN}" "${SCRIPT_DIR}/gcp_integration_api.py" \
            --realm "${REALM:-us1}" \
            --token-file "${TOKEN_FILE}" \
            --state-dir "${OUTPUT_DIR}/state" \
            --output "${OUTPUT_DIR}/state/current-state.json" \
            discover
        echo "==> Live state written to ${OUTPUT_DIR}/state/current-state.json"
        echo "==> Review and convert to a spec:"
        echo "    cp skills/${SKILL_NAME}/template.example template.observed.yaml"
        ;;
    rollback)
        if [[ -z "${REALM}" || -z "${INTEGRATION_ID}" ]]; then
            echo "ERROR: --rollback requires explicit --realm and --integration-id." >&2
            exit 2
        fi
        if [[ "${ROLLBACK_ACTION}" != "disable" && "${ROLLBACK_ACTION}" != "delete" ]]; then
            echo "ERROR: rollback action must be disable or delete." >&2
            exit 2
        fi
        if [[ "${ROLLBACK_INTEGRATION_ALIAS}" == "true" ]]; then
            echo "WARN: --rollback integration is deprecated; use --rollback disable." >&2
        fi
        if [[ "${APPLY_REQUESTED}" == "true" && "${ROLLBACK_ACTION_EXPLICIT}" != "true" ]]; then
            echo "ERROR: rollback action was not explicit; use --rollback disable or --rollback delete" >&2
            exit 2
        fi
        if [[ "${EXPECTED_ENABLED_STATE}" != "true" && "${EXPECTED_ENABLED_STATE}" != "false" ]]; then
            echo "ERROR: --expected-enabled-state must be true or false." >&2
            exit 2
        fi
        if [[ "${DRY_RUN}" == "true" ]]; then
            echo "ERROR: rollback is already render-only without --apply; do not combine it with --dry-run." >&2
            exit 2
        fi

        if [[ "${APPLY_REQUESTED}" != "true" ]]; then
            if [[ -z "${INTEGRATION_NAME}" ]]; then
                echo "ERROR: offline rollback render requires explicit --integration-name." >&2
                exit 2
            fi
            if [[ -z "${OBSERVED_STATE_FILE}" ]]; then
                echo "ERROR: offline rollback render requires explicit --observed-state-file." >&2
                exit 2
            fi
            assert_secret_file_perms "${OBSERVED_STATE_FILE}" "observed state snapshot"
            if [[ -n "${PLAN_SHA256}" || -n "${ACKNOWLEDGE_DISABLE}" || -n "${ACKNOWLEDGE_DELETE}" ]]; then
                echo "ERROR: offline rollback render does not accept --plan-hash or acceptance flags." >&2
                exit 2
            fi
            if [[ -n "${TOKEN_FILE}" || "${ALLOW_LOOSE_TOKEN_PERMS}" == "true" ]]; then
                echo "ERROR: offline rollback render does not accept token options." >&2
                exit 2
            fi
            credential_args=()
            if [[ "${ROLLBACK_ACTION}" == "disable" ]]; then
                if [[ ${#KEY_FILES[@]} -gt 0 && -n "${WIF_CONFIG_FILE}" ]]; then
                    echo "ERROR: disable plan render accepts either --key-file values or --wif-config-file, never both." >&2
                    exit 2
                fi
                if [[ ${#KEY_FILES[@]} -eq 0 && -z "${WIF_CONFIG_FILE}" ]]; then
                    echo "ERROR: disable plan render requires secure GCP credential files." >&2
                    exit 2
                fi
                for key_file in "${KEY_FILES[@]}"; do
                    assert_secret_file_perms "${key_file}" "GCP SA key"
                    credential_args+=(--key-file "${key_file}")
                done
                if [[ -n "${WIF_CONFIG_FILE}" ]]; then
                    assert_wif_config_file "${WIF_CONFIG_FILE}"
                    credential_args+=(--wif-config-file "${WIF_CONFIG_FILE}")
                fi
            elif [[ ${#KEY_FILES[@]} -gt 0 || -n "${WIF_CONFIG_FILE}" ]]; then
                echo "ERROR: delete rollback plans reject GCP credential files." >&2
                exit 2
            fi
            plan_result="$("${PYTHON_BIN}" "${SCRIPT_DIR}/gcp_integration_api.py" \
                --realm "${REALM}" \
                --state-dir "${OUTPUT_DIR}/state" \
                --plan-file "${PLAN_FILE}" \
                --integration-id "${INTEGRATION_ID}" \
                --integration-name "${INTEGRATION_NAME}" \
                --expected-enabled-state "${EXPECTED_ENABLED_STATE}" \
                --observed-state-file "${OBSERVED_STATE_FILE}" \
                "${credential_args[@]}" \
                rollback "${ROLLBACK_ACTION}")"
            echo "${plan_result}"
            rendered_plan_sha="$("${PYTHON_BIN}" -c 'import json,sys; print(json.load(sys.stdin)["plan_hash"])' <<<"${plan_result}")"
            echo "==> Rollback plan rendered offline to: ${PLAN_FILE}"
            echo "==> Review SHA-256: ${rendered_plan_sha}"
            echo "==> Apply this exact ${ROLLBACK_ACTION} plan only after review:"
            if [[ "${ROLLBACK_ACTION}" == "disable" ]]; then
                echo "    bash ${0} --rollback disable --apply --realm ${REALM} \\"
                echo "      --integration-id ${INTEGRATION_ID} --plan-file ${PLAN_FILE} --plan-hash ${rendered_plan_sha} \\"
                echo "      --accept-disable-integration ${INTEGRATION_ID} --token-file /secure/o11y-token \\"
                if [[ -n "${WIF_CONFIG_FILE}" ]]; then
                    echo "      --wif-config-file /secure/path/gcp_wif_config.json"
                else
                    echo "      --key-file /secure/gcp-sa-key.json  # repeat once per project"
                fi
            else
                echo "    bash ${0} --rollback delete --apply --realm ${REALM} \\"
                echo "      --integration-id ${INTEGRATION_ID} --plan-file ${PLAN_FILE} --plan-hash ${rendered_plan_sha} \\"
                echo "      --accept-delete-integration ${INTEGRATION_ID} --token-file /secure/o11y-token"
            fi
            exit 0
        fi

        if [[ "${ALLOW_LOOSE_TOKEN_PERMS}" == "true" ]]; then
            echo "ERROR: rollback mutation does not allow loose token permissions." >&2
            exit 2
        fi
        if [[ -n "${OBSERVED_STATE_FILE}" ]]; then
            echo "ERROR: rollback --apply uses the observed snapshot already bound in the plan." >&2
            exit 2
        fi
        if [[ -z "${TOKEN_FILE}" || -z "${PLAN_SHA256}" ]]; then
            echo "ERROR: rollback --apply requires --token-file and --plan-hash." >&2
            exit 2
        fi
        case "${ROLLBACK_ACTION}" in
            disable)
                if [[ "${ACKNOWLEDGE_DISABLE}" != "${INTEGRATION_ID}" || -n "${ACKNOWLEDGE_DELETE}" ]]; then
                    echo "ERROR: exactly --accept-disable-integration ${INTEGRATION_ID} is required." >&2
                    exit 2
                fi
                if [[ ${#KEY_FILES[@]} -gt 0 && -n "${WIF_CONFIG_FILE}" ]]; then
                    echo "ERROR: disable accepts either --key-file values or --wif-config-file, never both." >&2
                    exit 2
                fi
                if [[ ${#KEY_FILES[@]} -eq 0 && -z "${WIF_CONFIG_FILE}" ]]; then
                    echo "ERROR: disable requires explicit secure GCP credential files for payload reconstruction." >&2
                    exit 2
                fi
                for key_file in "${KEY_FILES[@]}"; do assert_secret_file_perms "${key_file}" "GCP SA key"; done
                [[ -n "${WIF_CONFIG_FILE}" ]] && assert_wif_config_file "${WIF_CONFIG_FILE}"
                ;;
            delete)
                if [[ "${ACKNOWLEDGE_DELETE}" != "${INTEGRATION_ID}" || -n "${ACKNOWLEDGE_DISABLE}" ]]; then
                    echo "ERROR: exactly --accept-delete-integration ${INTEGRATION_ID} is required." >&2
                    exit 2
                fi
                if [[ ${#KEY_FILES[@]} -gt 0 || -n "${WIF_CONFIG_FILE}" ]]; then
                    echo "ERROR: delete rollback rejects GCP credential files." >&2
                    exit 2
                fi
                ;;
        esac
        assert_secret_file_perms "${TOKEN_FILE}" "Splunk O11y token"
        rollback_args=(
            --realm "${REALM}"
            --token-file "${TOKEN_FILE}"
            --state-dir "${OUTPUT_DIR}/state"
            --plan-file "${PLAN_FILE}"
            --plan-hash "${PLAN_SHA256}"
            --integration-id "${INTEGRATION_ID}"
            --apply
        )
        [[ -n "${ACKNOWLEDGE_DISABLE}" ]] && rollback_args+=(--accept-disable-integration "${ACKNOWLEDGE_DISABLE}")
        [[ -n "${ACKNOWLEDGE_DELETE}" ]] && rollback_args+=(--accept-delete-integration "${ACKNOWLEDGE_DELETE}")
        for key_file in "${KEY_FILES[@]}"; do rollback_args+=(--key-file "${key_file}"); done
        [[ -n "${WIF_CONFIG_FILE}" ]] && rollback_args+=(--wif-config-file "${WIF_CONFIG_FILE}")
        "${PYTHON_BIN}" "${SCRIPT_DIR}/gcp_integration_api.py" "${rollback_args[@]}" rollback "${ROLLBACK_ACTION}"
        ;;
    list_services)
        "${PYTHON_BIN}" "${RENDERER}" --spec "${SPEC}" --output-dir "${OUTPUT_DIR}" --list-services
        ;;
    *)
        echo "Unknown mode: ${MODE}" >&2; usage 1
        ;;
esac
